# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Pliary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'FSCalendar'
  pod 'Kingfisher'
  pod 'SwiftyGif'
  pod 'Hero'
  pod 'lottie-ios'
  # Pods for Pliary
end
