# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Pliary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #pod 'GoogleSignIn'
  #pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'FSCalendar'
  pod 'Kingfisher'
  pod 'Hero'
  pod 'lottie-ios'
  # Pods for Pliary
end
